export const seoConfig = {
  siteName: "Ansh Agrawal Portfolio",
  title: "Ansh Agrawal Portfolio",
  description:
    "Software engineer building scalable full-stack web applications with React, Next.js, Node.js, Laravel, and cloud platforms (Azure and Google Cloud), with hands-on experience in CI/CD, automated testing, and performance optimization.",
  siteUrl: "https://anshagrawal.com",
  authorName: "Ansh Agrawal",
  jobTitle: "Software Engineer",
  linkedinUrl: "https://www.linkedin.com/in/anshagrawal6/",
  githubUrl: "https://github.com/aagra109",
  email: "ansh-agrawal@outlook.com",
  keywords: [
    "Ansh Agrawal",
    "Ansh Agrawal portfolio",
    "software engineer portfolio",
    "software engineer",
    "full-stack software engineer",
    "full-stack developer portfolio",
    "web application engineer",
    "React developer",
    "Next.js developer",
    "Node.js developer",
    "Laravel developer",
    "TypeScript developer",
    "cloud software engineer",
    "CI/CD engineer",
    "automated testing",
    "Google Cloud",
    "Azure developer",
  ],
  knowledgeAreas: [
    "TypeScript",
    "JavaScript",
    "Python",
    "Java",
    "PHP",
    "React",
    "Next.js",
    "Node.js",
    "Express.js",
    "Laravel",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Azure",
    "Google Cloud",
    "Docker",
    "GitHub Actions",
    "Playwright",
    "REST APIs",
  ],
};
